name: 'Docker Build'

on:
  push:
    tags:
      - v*
      - build-*

env:
  DOCKER_REGISTRY: 'rg.fr-par.scw.cloud'
  IMAGE_NAME: 'rg.fr-par.scw.cloud/youblive/brave'

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - name: 'Docker registry authentication'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build . -t ${IMAGE_NAME}:${GITHUB_REF##*/} -t ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:${GITHUB_REF##*/}
          docker push ${IMAGE_NAME}
